### PR TITLE
There should be no preference related to declaration of several vars

### PR DESCRIPTION
**Pull request by voldern**
There should be no preference on whether we declare several variables in the same var statement.
I think this matters very little, and can be left to personal preference. 

Using the var statement for each variable makes it easier to move the statement around or removing it. So I think a case also could be made for changing the rule so that one has to use a var statement for every variable. 

Thoughts?

### CODE REVIEW

**Comment by rexxars** [comment]
+1

**Comment by androa** [comment]
I think the same argument for the "use" statement in the PHP standard could be used. Having multiple declaration makes it very easy to move them around, but I don't thing it is a good use of the argument in this case?

Variables are usually declared in the correct scope and should stay there for any reasonable time, and are they moved, the remaining code should need refactoring as well. Use statements can actually be moved without implying further changes.

**Comment by voldern** [comment]
A lot of other javascript standards at least allow the declaration of variables further down the scope if the function returns early. My impression is also that the node community generally do not hoist variables manually.

**Comment by rexxars** [comment]
The way I am reading this, this doesn't really relate to hoisting variables, but rather if one should use one or more var statements when setting variables right after eachother.

``` js
var x = 0;
var y = 0;
var z = 1;

// vs
var x = 0,
    y = 0,
    z = 1;
```

And that the following is still allowed:

``` js
api.doSomething('blah', function(err, response) {
    var error = err || (response && response.error);
    if (error) {
        console.error('ZOMG ERROR', error);
        return;
    }

    var body = response.body;
    window.alert(body.message);
});
```

Correct me if I'm wrong in reading it this way.

**Comment by voldern** [comment]
Yeah, that's true. I was just responding to the comment from André which mentioned that people usually declare all the variables at the top of the scope so it's there is not so much to gain from making it easier to move the statements around.

**Comment by olekenneth** [comment]
I would say less `var`, less noise and easier to read. 

I would imagine reading:

``` javascript
var someThing = 'some string';
var someThang = 'some string';
var someThung = 'some string';
var someTheng = 'some string';
```

is harder to read than:

``` javascript
var someThing = 'some string',
    someThang = 'some string',
    someThung = 'some string',
    someTheng = 'some string';
```

**Pull request merged**
